### ISSUE TITLE
Is there a small model trainer, such as llama2.c?

### ISSUE THREAD

**Issue by win10ogod** [kyegomez/Gemini#4]
Is there a small model trainer, such as llama2.c?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/Gemini/issues/4">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/Gemini/issues/4/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/Gemini/issues/4/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@win10ogod what do you mean,? A trainer to train this model? You should try making a script to train it we need help there

**Comment by win10ogod** [comment]
> llama2.c

I believe it would be beneficial to introduce a training program akin to llama2.c to enhance understanding of this project among a wider audience. Not everyone involved may have an engineering background or be an expert in this field.

**Comment by win10ogod** [comment]
We can use simple training projects to train models that can use voice dialogue, which will help the project become more widely known.

**Comment by kyegomez** [comment]
@win10ogod Yeah good idea, can you help make this happen I'm still smoothening out some rough spots?

**Comment by win10ogod** [comment]
@kyegomez 
Hello, please refer to the code in llama2.c. As long as you can truly implement the project.

**Comment by kyegomez** [comment]
@win10ogod submit a pull request for the training code, the implementation is complete

**Comment by win10ogod** [comment]
> @win10ogod submit a pull request for the training code, the implementation is complete

Which pull request is it? Can you provide a link?

**Comment by win10ogod** [comment]
@kyegomez
