### ISSUE TITLE
[BUG] Import Error

### ISSUE THREAD

**Issue by corous** [kyegomez/Gemini#7]
**Describe the bug**
Getting the following error when running the example code.

##Code##
import torch 
from gemini_torch import Gemini

# Initialize the model
model = Gemini(
    num_tokens=50432,
    max_seq_len=8192,
    dim=2560,
    depth=32,
    dim_head=128,
    heads=24,
    use_abs_pos_emb=False,
    alibi_pos_bias=True,
    alibi_num_heads=12,
    rotary_xpos=True,
    attn_flash=True,
    attn_kv_heads=2,
    qk_norm=True,
    attn_qk_norm=True,
    attn_qk_norm_dim_scale=True,
)

# Initialize the text random tokens
x = torch.randint(0, 50432, (1, 8192))

# Apply model to x
y = model(x)

# Print logits
print(y)

##Error below##
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 2>()
      1 import torch 
----> 2 from gemini_torch import Gemini
      4 # Initialize the model
      5 model = Gemini(
      6     num_tokens=50432,
      7     max_seq_len=8192,
   (...)
     20     attn_qk_norm_dim_scale=True,
     21 )

File E:\Anaconda3\lib\site-packages\gemini_torch\__init__.py:2, in <module>
      1 from gemini_torch.model import Gemini
----> 2 from gemini_torch.utils import ImgToTransformer, AudioToTransformer
      3 from gemini_torch.tokenizer import MultimodalSentencePieceTokenizer
      5 __all__ = [
      6     "Gemini",
      7     "ImgToTransformer",
      8     "AudioToTransformer",
      9     "MultimodalSentencePieceTokenizer",
     10 ]

ImportError: cannot import name 'AudioToTransformer' from 'gemini_torch.utils' (E:\Anaconda3\lib\site-packages\gemini_torch\utils.py)

**To Reproduce**
1. Install the library by following the Readme.md
2. Run the example.py in JupyterNotebooks
3. See error

**Expected behavior**
The program displays a matrix.

Screenshot attached.
![Gemini_Torch_error](https://github.com/kyegomez/Gemini/assets/70595494/37ddfe0d-d8bb-4860-ba60-66197299574f)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/Gemini/issues/7">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/Gemini/issues/7/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/Gemini/issues/7/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@corous this bug has been eliminated
