### ISSUE TITLE
[BUG] Getting CPU allocation error after the update on 12/15/2023

### ISSUE THREAD

**Issue by corous** [kyegomez/Gemini#8]
**Describe the bug**
Already installed the update on 12/15/2023 via "pip3 install gemini-torch --upgrade". Running the example code generates the following error.  -- Maybe Torch cannot be forced to run on the GPU? I have an NVidia GeForce RTX 2070.

"RuntimeError: [enforce fail at alloc_cpu.cpp:80] data. DefaultCPUAllocator: not enough memory: you tried to allocate 21152713932800 bytes."

**To Reproduce**
1. Install Gemini-Torch per Readme.md
2. Run the example.py
3. See error

**Expected behavior**
The example completes without error and displays a matrix.

**Screenshots**
Please see screenshots attached.

![Gemini_Torch_error02](https://github.com/kyegomez/Gemini/assets/70595494/1ab80e35-616d-471c-9093-350c4f6fa01a)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/Gemini/issues/8">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/Gemini/issues/8/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/Gemini/issues/8/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@corous try to use a better cpu this a big model I can try adding dynamic cpu usage but it will take some time

**Comment by corous** [comment]
Got it. 

So, there’s no way to force it to run on the GPU? Or, reduce the dimension / parameters or size of the model to allow it to run? 

If not, I can run out to buy myself a new CPU for Christmas. Or maybe run it on a VM.

**Comment by kyegomez** [comment]
@corous yes just lower the dimension and depth and sequence length and maybe vocabulary size and it should work

**Comment by corous** [comment]
Thank you so much. I really appreciate this implementation and your hard work on responding to the issues.

So, I reduced the dimension, depth, sequence length and max tokens (I'm guessing this is what you meant by vocabulary size). I'm getting a "Failed in forward method:  too many values to unpack (expected 5)" error now. 

The code and error message are copied and pasted below.

-----------------------------------------------
Code:

import torch 
from gemini_torch import Gemini


# Initialize the model
model = Gemini(
    num_tokens=4096,
    max_seq_len=1024,
    dim=256,
    depth=8,
    dim_head=128,
    heads=24,
    use_abs_pos_emb=False,
    alibi_pos_bias=True,
    alibi_num_heads=12,
    rotary_xpos=True,
    attn_flash=True,
    attn_kv_heads=2,
    qk_norm=True,
    attn_qk_norm=True,
    attn_qk_norm_dim_scale=True,
)

# Initialize the text random tokens
x = torch.randint(0, 4096, (1, 1024))

# Apply model to x
y = model(x)

# Print logits
print(y)

-----------------------------------------------
Error:

Failed in forward method:  too many values to unpack (expected 5)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [2], in <cell line: 28>()
     25 x = torch.randint(0, 4096, (1, 1024))
     27 # Apply model to x
---> 28 y = model(x)
     30 # Print logits
     31 print(y)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File E:\Anaconda3\lib\site-packages\gemini_torch\model.py:158, in Gemini.forward(self, text, img, audio, *args, **kwargs)
    155     else:
    156         model_input = self.decoder.forward(text)[0]
--> 158     return self.decoder(model_input, padded_x=model_input[0])
    159 except Exception as e:
    160     print("Failed in forward method: ", e)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File E:\Anaconda3\lib\site-packages\zeta\structs\auto_regressive_wrapper.py:320, in AutoregressiveWrapper.forward(self, x, return_loss, **kwargs)
    317     mask = ~torch.zeros_like(inp).scatter(1, indices, 1.0).bool()
    318     kwargs.update(self_attn_context_mask=mask)
--> 320 logits = self.net(inp, **kwargs)
    322 loss = F.cross_entropy(
    323     rearrange(logits, "b n c -> b c n"),
    324     target,
    325     ignore_index=ignore_index,
    326 )
    328 if return_loss:

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File E:\Anaconda3\lib\site-packages\gemini_torch\transformer.py:1599, in Transformer.forward(self, x, return_embeddings, return_logits_and_embeddings, return_intermediates, mask, return_mems, return_attn, mems, pos, prepend_embeds, sum_embeds, return_attn_z_loss, attn_z_loss_weight, **kwargs)
   1582 def forward(
   1583     self,
   1584     x,
   (...)
   1597     **kwargs,
   1598 ):
-> 1599     b, n, device, num_mem, emb_frac_gradient = (
   1600         *x.shape,
   1601         x.device,
   1602         self.num_memory_tokens,
   1603         self.emb_frac_gradient,
   1604     )
   1605     return_hiddens = (
   1606         return_mems | return_attn | return_intermediates | return_attn_z_loss
   1607     )
   1609     # absolute positional embedding

ValueError: too many values to unpack (expected 5)

**Comment by kyegomez** [comment]
@corous I just tried fixing it by removing [0] in the forward method, try it out and lmk if it works for you

**Comment by corous** [comment]
Hey @kyegomez, thank you for the continued support and prompt response. 

I ran a "pip3 install gemini-torch --upgrade". 

Now I'm getting a "'tuple' object has no attribute 'shape'" error. 

-------------------------------------------
Code:

import torch 
from gemini_torch import Gemini


# Initialize the model
model = Gemini(
    num_tokens=4096,
    max_seq_len=1024,
    dim=256,
    depth=8,
    dim_head=128,
    heads=24,
    use_abs_pos_emb=False,
    alibi_pos_bias=True,
    alibi_num_heads=12,
    rotary_xpos=True,
    attn_flash=True,
    attn_kv_heads=2,
    qk_norm=True,
    attn_qk_norm=True,
    attn_qk_norm_dim_scale=True,
)

# Initialize the text random tokens
x = torch.randint(0, 4096, (1, 1024))

# Apply model to x
y = model(x)

# Print logits
print(y)


-------------------------------------------
Error: 

Failed in forward method:  'tuple' object has no attribute 'shape'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [1], in <cell line: 28>()
     25 x = torch.randint(0, 4096, (1, 1024))
     27 # Apply model to x
---> 28 y = model(x)
     30 # Print logits
     31 print(y)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File E:\Anaconda3\lib\site-packages\gemini_torch\model.py:158, in Gemini.forward(self, text, img, audio, *args, **kwargs)
    155     else:
    156         model_input = self.decoder.forward(text)
--> 158     return self.decoder(model_input, padded_x=model_input)
    159 except Exception as e:
    160     print("Failed in forward method: ", e)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File E:\Anaconda3\lib\site-packages\zeta\structs\auto_regressive_wrapper.py:307, in AutoregressiveWrapper.forward(self, x, return_loss, **kwargs)
    284 def forward(self, x, return_loss=True, **kwargs):
    285     """
    286     Forward pass of the autoregressive wrapper.
    287 
   (...)
    305 
    306     """
--> 307     seq, ignore_index = x.shape[1], self.ignore_index
    309     inp, target = x[:, :-1], x[:, 1:]
    311     if self.mask_prob > 0.0:

AttributeError: 'tuple' object has no attribute 'shape'

**Comment by kyegomez** [comment]
@corous i think i might have fixed it but i don't know forsure please try again. It consumes too much memory even for me

**Comment by corous** [comment]
@kyegomez  Hey, I ran a "pip3 install gemini-torch --upgrade", but it doesn't look like anything got updated during the process. I'm also still getting the "Failed in forward method:  'tuple' object has no attribute 'shape'" error. 

------------------------------------
Code: 

import torch 
from gemini_torch import Gemini


# Initialize the model
model = Gemini(
    num_tokens=4096,
    max_seq_len=1024,
    dim=256,
    depth=8,
    dim_head=128,
    heads=24,
    use_abs_pos_emb=False,
    alibi_pos_bias=True,
    alibi_num_heads=12,
    rotary_xpos=True,
    attn_flash=True,
    attn_kv_heads=2,
    qk_norm=True,
    attn_qk_norm=True,
    attn_qk_norm_dim_scale=True,
)

# Initialize the text random tokens
x = torch.randint(0, 4096, (1, 1024))

# Apply model to x
y = model(x)

# Print logits
print(y)

------------------------------------
Error:

Failed in forward method:  'tuple' object has no attribute 'shape'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [1], in <cell line: 28>()
     25 x = torch.randint(0, 4096, (1, 1024))
     27 # Apply model to x
---> 28 y = model(x)
     30 # Print logits
     31 print(y)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File E:\Anaconda3\lib\site-packages\gemini_torch\model.py:158, in Gemini.forward(self, text, img, audio, *args, **kwargs)
    155     else:
    156         model_input = self.decoder.forward(text)
--> 158     return self.decoder(model_input, padded_x=model_input)
    159 except Exception as e:
    160     print("Failed in forward method: ", e)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File E:\Anaconda3\lib\site-packages\zeta\structs\auto_regressive_wrapper.py:307, in AutoregressiveWrapper.forward(self, x, return_loss, **kwargs)
    284 def forward(self, x, return_loss=True, **kwargs):
    285     """
    286     Forward pass of the autoregressive wrapper.
    287 
   (...)
    305 
    306     """
--> 307     seq, ignore_index = x.shape[1], self.ignore_index
    309     inp, target = x[:, :-1], x[:, 1:]
    311     if self.mask_prob > 0.0:

AttributeError: 'tuple' object has no attribute 'shape'

![Gemini_Torch_error05](https://github.com/kyegomez/Gemini/assets/70595494/8b24f2da-be28-4618-9307-da29e61bc7d3)

![Gemini_Torch_error06](https://github.com/kyegomez/Gemini/assets/70595494/afad313e-acc4-47ae-a36b-de8da634abae)

**Comment by kyegomez** [comment]
@corous please forgive me there was a whole vast array of issues trying to enable omni-modality transformation from multiple dimensions into text dimension, it should work now, but there may be alot of room for optimization please let me know what you think. in the model file!

**Comment by corous** [comment]
@kyegomez   No worries. Totally understand. I tried it once last week and again today. Restarting and doing a "pip install gemini-torch --upgrade" both times.

I'm getting the error below now. If it's too much trouble to account for multi-modal, no worries. I will just try to run it on a different VM environment. 

![Gemini-Torch-Error05](https://github.com/kyegomez/Gemini/assets/70595494/57f6aafc-945d-4221-b13f-eb860883898d)

**Comment by kyegomez** [comment]
@corous hey try again the implementation has been completed
